name: Deploy to Server

on:
  push:
    branches:
      - master # Asegúrate de cambiar esto al nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Usa la versión de Node.js que necesites

      - name: Install dependencies
        run: npm ci

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd D:/Proyectos/Node
            git pull
            npm ci
            pm2 restart bot.js
